"""Application constants"""

# User roles
ROLE_ADMIN = "admin"
ROLE_USER = "user"
ROLE_GUEST = "guest"

USER_ROLES = [ROLE_ADMIN, ROLE_USER, ROLE_GUEST]

# Document status
DOC_STATUS_PENDING = "pending"
DOC_STATUS_PROCESSING = "processing"
DOC_STATUS_COMPLETED = "completed"
DOC_STATUS_FAILED = "failed"

DOC_STATUSES = [DOC_STATUS_PENDING, DOC_STATUS_PROCESSING, DOC_STATUS_COMPLETED, DOC_STATUS_FAILED]

# File types
FILE_TYPE_PDF = "pdf"
FILE_TYPE_DOCX = "docx"
FILE_TYPE_TXT = "txt"
FILE_TYPE_MD = "md"
FILE_TYPE_HTML = "html"

SUPPORTED_FILE_TYPES = [FILE_TYPE_PDF, FILE_TYPE_DOCX, FILE_TYPE_TXT, FILE_TYPE_MD, FILE_TYPE_HTML]

# Chunk strategy
CHUNK_STRATEGY_BY_TITLE = "by_title"
CHUNK_STRATEGY_BY_PARAGRAPH = "by_paragraph"
CHUNK_STRATEGY_BY_PAGE = "by_page"

CHUNK_STRATEGIES = [CHUNK_STRATEGY_BY_TITLE, CHUNK_STRATEGY_BY_PARAGRAPH, CHUNK_STRATEGY_BY_PAGE]

# Permissions
PERMISSION_READ = "read"
PERMISSION_WRITE = "write"
PERMISSION_DELETE = "delete"
PERMISSION_SHARE = "share"

DOCUMENT_PERMISSIONS = [PERMISSION_READ, PERMISSION_WRITE, PERMISSION_DELETE, PERMISSION_SHARE]

# Pagination
DEFAULT_PAGE = 1
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

# RAG
DEFAULT_TOP_K = 5
MAX_TOP_K = 20
MIN_SIMILARITY_THRESHOLD = 0.3

# API
API_V1_PREFIX = "/api/v1"